version: '3.5'
services:
  n1:
    image: nginx:alpine
    volumes:
      - /opt/inetlinux.com/var/www:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      vpcbr:
        ipv4_address: 10.1.0.2
  n2:
    image: nginx:alpine
    volumes:
      - /opt/inetlinux.com/var/www:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      vpcbr:
        ipv4_address: 10.1.0.3
  n3:
    image: nginx:alpine
    volumes:
      - /opt/inetlinux.com/var/www:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      vpcbr:
        ipv4_address: 10.1.0.4

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16
